#!/bin/bash
set -e
source $(dirname "$0")/build

mkdir -pv web web-tmp

# Prepare libraries for stitching
mkdir -p web-tmp/gamma

i=node_modules/gamma/index.js ; o=web-tmp/gamma/gamma.js
[ $i -nt $o ] && echo "Copying $i to $o" && cp $i $o

# Stitch
stitched=web-tmp/apl-stitched.js
for f in $(find src -name '*.coffee'); do
    if [ $f -nt $stitched ]; then
        echo "Stitching to $stitched"
        node >$stitched <<EOF
            require('stitch')
                .createPackage({paths: ['lib', 'web-tmp/gamma']})
                .compile(function (err, source) {
                    if (err) { throw err; }
                    process.stdout.write(source);
                });
EOF
        break
    fi
done

i=web-src/index.coffee ; o=web-tmp/index.js
[ $i -nt $o ] && echo "Compiling $i" && node_modules/.bin/coffee --macro -b -o $(dirname $o) -c $i

i=web-src/index.html ; o=web/index.html
[ $i -nt $o ] && echo "Copying $i to $o" && cp $i $o

i=web-src/apl385.ttf ; o=web/apl385.ttf
[ $i -nt $o ] && echo "Copying $i to $o" && cp $i $o

i=web-src/tipsy.gif ; o=web/tipsy.gif
[ $i -nt $o ] && echo "Copying $i to $o" && cp $i $o

i=web-src/examples-gen.coffee ; o=web-tmp/examples-gen.js
[ $i -nt $o ] && echo "Compiling $i" && node_modules/.bin/coffee --macro -b -o $(dirname $o) -c $i

i=web-tmp/examples-gen.js ; o=web-tmp/examples.js
[ $i -nt $o ] && echo "Generating $o" && node $i

i=test/collectdoctests.coffee ; o=${i%.coffee}.js
[ $i -nt $o ] && echo "Compiling $i" && node_modules/.bin/coffee -abc $i

i=test/rundoctest.coffee ; o=${i%.coffee}.js
[ $i -nt $o ] && echo "Compiling $i" && node_modules/.bin/coffee -abc $i

i=test/rundoctests.coffee ; o=${i%.coffee}.js
[ $i -nt $o ] && echo "Compiling $i" && node_modules/.bin/coffee -abc $i

echo 'Collecting all JS into web/all.js'
(
    cat $stitched                                   \
        web-src/jquery.min.js                       \
        web-src/jquery.fieldselection.min.js        \
        web-src/jquery.keyboard.js                  \
        web-src/jquery.keyboard.extension-typing.js \
        web-src/jquery.tipsy.js                     \
        web-tmp/examples.js                         \
        web-tmp/index.js                            \
        test/rundoctest.js
    echo -n 'var aplTests = '
    node test/collectdoctests.js
) >web/all.js

echo 'Collecting all CSS into web/all.css'
cat web-src/index.css    \
    web-src/keyboard.css \
    web-src/tipsy.css    \
    web-src/apl385.css   \
        > web/all.css
