#!/bin/bash
set -e
source $(dirname "$0")/build-web

mkdir -pv downloads

i=web-tmp/apl-stitched.js ; o=downloads/apl.js
if [ $i -nt $o ]; then
    echo "Creating $o"
    cp $i $o
    echo 'var apl = require("apl");' >>$o
fi

true
