#!/bin/bash
set -ev
cd $(dirname "$0")

[ "$(git rev-parse --abbrev-ref HEAD)" == master ] \
    || (echo 'This is not the master branch.' ; exit 1)

rm -rf web m
git checkout gh-pages
git merge master
./build-web
./build-m
if [ -n "$(git status m web --porcelain)" ]; then
    git add web m
    git commit -a -m 'built demo'
fi
git checkout master
