// Generated by CoffeeScript 1.4.0
var exports;

exports = module.exports = function(f) {
  var compile;
  if (typeof f !== 'function') {
    compile = require('./compiler').compile;
    f = new Function(compile(f).jsOutput);
  }
  return f(require('./builtins').builtins);
};
