// Generated by CoffeeScript 1.4.0
var exports;

exports = module.exports = function(aplSource) {
  return require('./compiler').exec(aplSource);
};

exports.createGlobalContext = function() {
  return require('./helpers').inherit(require('./builtins').builtins);
};
