// Generated by CoffeeScript 1.4.0
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['./vocabulary', './helpers'], function(vocabularyModule, helpers) {
  var browserVocabulary, ctx, inherit, vocabulary;
  vocabulary = vocabularyModule.vocabulary;
  inherit = helpers.inherit;
  browserVocabulary = ctx = inherit(vocabulary);
  ctx['⍵'] = ('' + location).split('');
  ctx['get_⎕'] = function() {
    return (prompt('⎕:') || '').split('');
  };
  ctx['set_⎕'] = function(x) {
    return alert(x);
  };
  ctx['get_⍞'] = function() {
    return (prompt() || '').split('');
  };
  ctx['set_⍞'] = function(x) {
    return alert(x);
  };
  return {
    browserVocabulary: browserVocabulary
  };
});
