// Generated by CoffeeScript 1.3.3
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['./builtins', './helpers'], function(builtinsModule, helpers) {
  var builtins, ctx, inherit;
  builtins = builtinsModule.builtins;
  inherit = helpers.inherit;
  exports.browserBuiltins = ctx = inherit(builtins);
  ctx['⍵'] = ('' + location).split('');
  ctx['get_⎕'] = function() {
    return (prompt('⎕:') || '').split('');
  };
  ctx['set_⎕'] = function(x) {
    return alert(x);
  };
  ctx['get_⍞'] = function() {
    return (prompt() || '').split('');
  };
  return ctx['set_⍞'] = function(x) {
    return alert(x);
  };
});
