// Generated by CoffeeScript 1.4.0
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(['./helpers'], function(helpers) {
  var C, Complex, assert, die;
  die = helpers.die, assert = helpers.assert;
  C = function(re, im) {
    if (im) {
      return new Complex(re, im);
    } else {
      return re;
    }
  };
  Complex = (function() {

    function Complex(re, im) {
      this.re = re != null ? re : 0;
      this.im = im != null ? im : 0;
      assert(typeof this.re === 'number');
      assert(typeof this.im === 'number');
    }

    Complex.prototype.toString = function() {
      return ("" + this.re + "J" + this.im).replace(/-/g, '¯');
    };

    Complex.prototype['='] = function(x) {
      return +((x instanceof Complex) && x.re === this.re && x.im === this.im);
    };

    Complex.prototype['≡'] = function(x) {
      return this['='](x);
    };

    Complex.prototype['+'] = function(x) {
      if (x != null) {
        if (typeof x === 'number') {
          return C(this.re + x, this.im);
        } else if (x instanceof Complex) {
          return C(this.re + x.re, this.im + x.im);
        } else {
          throw Error('Unsupported operation');
        }
      } else {
        return C(this.re, -this.im);
      }
    };

    Complex.prototype['−'] = function(x) {
      if (x != null) {
        if (typeof x === 'number') {
          return C(this.re - x, this.im);
        } else if (x instanceof Complex) {
          return C(this.re - x.re, this.im - x.im);
        } else {
          throw Error('Unsupported operation');
        }
      } else {
        return C(-this.re, -this.im);
      }
    };

    Complex.prototype['×'] = function(x) {
      if (x != null) {
        if (typeof x === 'number') {
          return C(x * this.re, x * this.im);
        } else if (x instanceof Complex) {
          return C(this.re * x.re - this.im * x.im, this.re * x.im + this.im * x.re);
        } else {
          throw Error('Unsupported operation');
        }
      } else {
        throw Error('Unsupported operation');
      }
    };

    Complex.prototype['÷'] = function(x) {
      var d;
      if (x != null) {
        if (typeof x === 'number') {
          return C(this.re / x, this.im / x);
        } else if (x instanceof Complex) {
          d = this.re * this.re + this.im * this.im;
          return C((this.re * x.re + this.im * x.im) / d, (this.re * x.im - this.im * x.re) / d);
        } else {
          throw Error('Unsupported operation');
        }
      } else {
        d = this.re * this.re + this.im * this.im;
        return C(this.re / d, -this.im / d);
      }
    };

    return Complex;

  })();
  return {
    Complex: Complex
  };
});
