// Generated by CoffeeScript 1.4.0
var define;

if (typeof define !== 'function') {
  define = require('amdefine')(module);
}

define(function() {
  var assert, die, inherit, isSimple, prod, prototypeOf, repeat, shapeOf, sum, withPrototype, withPrototypeCopiedFrom, withShape;
  inherit = function(x, extraProperties) {
    var f, k, r, v;
    if (extraProperties == null) {
      extraProperties = {};
    }
    f = (function() {});
    f.prototype = x;
    r = new f;
    for (k in extraProperties) {
      v = extraProperties[k];
      r[k] = v;
    }
    return r;
  };
  isSimple = function(x) {
    return !(x instanceof Array);
  };
  shapeOf = function(a) {
    return a.shape || ((a.length != null) && !(typeof a === 'string' && a.length === 1) ? [a.length] : []);
  };
  withShape = function(shape, a) {
    assert((!(shape != null)) || a.length === prod(shape));
    if ((shape != null) && shape.length !== 1) {
      a.shape = shape;
    }
    return a;
  };
  prototypeOf = function(x) {
    var p;
    if (typeof x === 'number') {
      return 0;
    } else if (typeof x === 'string') {
      return ' ';
    } else if (x.aplPrototype != null) {
      return x.aplPrototype;
    } else if (isSimple(x) || !x.length) {
      return 0;
    } else if (isSimple(x[0])) {
      return prototypeOf(x[0]);
    } else {
      p = prototypeOf(x[0]);
      return withShape(shapeOf(x[0]), (function() {
        var _i, _ref, _results;
        _results = [];
        for (_i = 0, _ref = x[0].length; 0 <= _ref ? _i < _ref : _i > _ref; 0 <= _ref ? _i++ : _i--) {
          _results.push(p);
        }
        return _results;
      })());
    }
  };
  withPrototype = withPrototype = function(p, x) {
    if ((x instanceof Array) && (!x.length) && (p !== 0)) {
      x.aplPrototype = p;
    }
    return x;
  };
  withPrototypeCopiedFrom = function(y, x) {
    if (x instanceof Array && !x.length) {
      withPrototype(prototypeOf(y), x);
    }
    return x;
  };
  sum = function(xs) {
    var r, x, _i, _len;
    r = 0;
    for (_i = 0, _len = xs.length; _i < _len; _i++) {
      x = xs[_i];
      r += x;
    }
    return r;
  };
  prod = function(xs) {
    var r, x, _i, _len;
    r = 1;
    for (_i = 0, _len = xs.length; _i < _len; _i++) {
      x = xs[_i];
      r *= x;
    }
    return r;
  };
  repeat = function(s, n) {
    var r, _i;
    r = '';
    for (_i = 0; 0 <= n ? _i < n : _i > n; 0 <= n ? _i++ : _i--) {
      r += s;
    }
    return r;
  };
  die = function(s) {
    throw Error(s);
  };
  assert = function(flag, s) {
    if (s == null) {
      s = 'Assertion failed';
    }
    if (!flag) {
      throw Error(s);
    }
  };
  return {
    inherit: inherit,
    isSimple: isSimple,
    shapeOf: shapeOf,
    withShape: withShape,
    prototypeOf: prototypeOf,
    withPrototype: withPrototype,
    withPrototypeCopiedFrom: withPrototypeCopiedFrom,
    sum: sum,
    prod: prod,
    repeat: repeat,
    die: die,
    assert: assert
  };
});
