macro -> macro.fileToNode 'src/macros.coffee'
macro -> macro.fileToNode 'src/helpers.coffee'
macro -> macro.fileToNode 'src/errors.coffee'
macro -> macro.fileToNode 'src/array.coffee'
macro -> macro.fileToNode 'src/complex.coffee'
macro -> macro.fileToNode 'src/lexer.coffee'
macro -> macro.fileToNode 'src/parser.coffee'
macro -> macro.fileToNode 'src/vocabulary.coffee'
macro -> macro.fileToNode 'src/vocabulary/vhelpers.coffee'
macro -> macro.fileToNode 'src/vocabulary/arithmetic.coffee'
macro -> macro.fileToNode 'src/vocabulary/backslash.coffee'
macro -> macro.fileToNode 'src/vocabulary/circle.coffee'
macro -> macro.fileToNode 'src/vocabulary/comma.coffee'
macro -> macro.fileToNode 'src/vocabulary/commute.coffee'
macro -> macro.fileToNode 'src/vocabulary/comparisons.coffee'
macro -> macro.fileToNode 'src/vocabulary/compose.coffee'
macro -> macro.fileToNode 'src/vocabulary/cupcap.coffee'
macro -> macro.fileToNode 'src/vocabulary/decode.coffee'
macro -> macro.fileToNode 'src/vocabulary/disclose.coffee'
macro -> macro.fileToNode 'src/vocabulary/dot.coffee'
macro -> macro.fileToNode 'src/vocabulary/drop.coffee'
macro -> macro.fileToNode 'src/vocabulary/each.coffee'
macro -> macro.fileToNode 'src/vocabulary/enclose.coffee'
macro -> macro.fileToNode 'src/vocabulary/encode.coffee'
macro -> macro.fileToNode 'src/vocabulary/epsilon.coffee'
macro -> macro.fileToNode 'src/vocabulary/exclamation.coffee'
macro -> macro.fileToNode 'src/vocabulary/execute.coffee'
macro -> macro.fileToNode 'src/vocabulary/find.coffee'
macro -> macro.fileToNode 'src/vocabulary/floorceil.coffee'
macro -> macro.fileToNode 'src/vocabulary/forkhook.coffee'
macro -> macro.fileToNode 'src/vocabulary/format.coffee'
macro -> macro.fileToNode 'src/vocabulary/grade.coffee'
macro -> macro.fileToNode 'src/vocabulary/identity.coffee'
macro -> macro.fileToNode 'src/vocabulary/iota.coffee'
macro -> macro.fileToNode 'src/vocabulary/logic.coffee'
macro -> macro.fileToNode 'src/vocabulary/poweroperator.coffee'
macro -> macro.fileToNode 'src/vocabulary/quad.coffee'
macro -> macro.fileToNode 'src/vocabulary/question.coffee'
macro -> macro.fileToNode 'src/vocabulary/rho.coffee'
macro -> macro.fileToNode 'src/vocabulary/rotate.coffee'
macro -> macro.fileToNode 'src/vocabulary/slash.coffee'
macro -> macro.fileToNode 'src/vocabulary/special.coffee'
macro -> macro.fileToNode 'src/vocabulary/squish.coffee'
macro -> macro.fileToNode 'src/vocabulary/tack.coffee'
macro -> macro.fileToNode 'src/vocabulary/take.coffee'
macro -> macro.fileToNode 'src/vocabulary/transpose.coffee'
macro -> macro.fileToNode 'src/vocabulary/variant.coffee'
macro -> macro.fileToNode 'src/vocabulary/zilde.coffee'
macro -> macro.fileToNode 'src/compiler.coffee'

apl = (aplCode) -> exec aplCode
apl.createGlobalContext = -> Object.create vocabulary
apl.approx = approx
if module? then module.exports = apl else @apl = apl
