# This module's `exports` is what `require('apl')` will return in node.js

# The module is callable, so that this would work:
#
#     #!/usr/bin/env node
#     require('apl')('⎕ ← "Hell, oh, world!"');
exports = module.exports = (aplSource) ->
  require('./compiler').exec aplSource

# JavaScript generated by the APL compiler needs `createGlobalContext()` for
# bootstrapping.
exports.createGlobalContext = ->
  Object.create require './vocabulary'

# A `compile()` method is exposed so it can be called by
# [coffee-subscript](https://github.com/ngn/coffee-subscript#readme) and
# others.
compile = require("./compiler").compile
exports.compile = (code) -> "(function(){#{compile code, embedded: true}})()" 
exports.fn = compile: (code) -> "function(){#{compile code, embedded: true}}"
